"""
RORB .catg writer — nodes-only (v2.26).

Writes a RORB GE 6.45 catchment file from a nodes dict.
Nodes are ordered by their integer key (= id field value from the input layer),
so the user's id directly determines the RORB node number.
A minimal control vector joins all sub-areas at the outlet for inspection.
Reaches are not included yet.

nodes dict structure:
  {int_id: {
      'x', 'y'         : coordinates (map CRS)
      'node_type'      : 1/2 = sub-area   3/4 = junction   0 = outlet
      'name'           : display label
      'area'           : km² (sub-areas only)
      'fi'             : impervious fraction 0–1 (sub-areas only)
      'print_node'     : bool
      'print_code'     : 70 / 71 / 72
      'location'       : location name when print_node is True
  }}
"""


def write_catg(nodes, path, title="RORB Catchment"):
    text = _build_catg(nodes, title)
    with open(path, 'w', newline='\r\n') as f:
        f.write(text)


# ── internals ─────────────────────────────────────────────────────────────────

def _build_catg(nodes, title):
    if not nodes:
        raise ValueError("No nodes to export.")

    # Sub-areas first (types 1, 2), then junctions/outlet (types 3, 4, 0).
    # Sorted by key so the user's id field determines RORB node numbering.
    sub_ids = sorted(nid for nid, n in nodes.items() if n['node_type'] in (1, 2))
    jnc_ids = sorted(nid for nid, n in nodes.items() if n['node_type'] in (0, 3, 4))
    ordered  = sub_ids + jnc_ids

    outlet_id = next((nid for nid in jnc_ids if nodes[nid]['node_type'] == 0), None)

    # Sequential RORB node IDs — 1-based, sub-areas first
    rorb_id = {nid: k + 1 for k, nid in enumerate(ordered)}

    # Normalise coordinates to the 2.5–97.5 display range
    all_x = [n['x'] for n in nodes.values()]
    all_y = [n['y'] for n in nodes.values()]
    mnx, mxx = min(all_x), max(all_x)
    mny, mxy = min(all_y), max(all_y)
    rx = mxx - mnx or 1.0
    ry = mxy - mny or 1.0
    def nx(x): return 2.5 + 95.0 * (x - mnx) / rx
    def ny(y): return 2.5 + 95.0 * (y - mny) / ry

    nv = len(nodes)
    L  = []

    # ── header ───────────────────────────────────────────────────────────────
    L += [
        f"{title:<69}",
        "C RORB_GE 6.45",
        "C WARNING - DO NOT EDIT THIS FILE OUTSIDE RORB TO ENSURE BOTH GRAPHICAL AND CATCHMENT DATA ARE COMPATIBLE WITH EACH OTHER",
        "C THIS FILE CANNOT BE OPENED IN EARLIER VERSIONS OF RORB GE - CURRENT VERSION IS v6.45",
        "C ",
        f"C {title:<69}",
        "C ",
        "C #FILE COMMENTS",
        "C   0",
        "C ",
        "C #SUB-AREA AREA COMMENTS",
        "C   0",
        "C ",
        "C #IMPERVIOUS FRACTION COMMENTS",
        "C   0",
        "C ",
        "C #BACKGROUND IMAGE",
        "C  T  F",
        "C ",
    ]

    # ── #NODES ───────────────────────────────────────────────────────────────
    L.append("C #NODES")
    L.append(f"C     {nv}")

    sub_counter = 0
    for nid in ordered:
        n   = nodes[nid]
        rid = rorb_id[nid]
        x   = nx(n['x'])
        y   = ny(n['y'])
        pc  = n['print_code'] if n['print_node'] else 0

        if n['node_type'] in (1, 2):
            sub_counter += 1
            L.append(
                f"C     {rid:>2}         {x:>8.3f}         {y:>8.3f}"
                f"          1.000 1 0     0 {sub_counter:<2}                         "
                f" {n['area']:>12.6f}       {n['fi']:>8.6f} {pc:>2}  0  0"
            )
            L.append(f"C {n['name']:<50}")

        elif n['node_type'] == 0:
            pc_out = pc if n['print_node'] else 70
            loc    = n['location'] or n['name'] or "Outlet"
            L.append(
                f"C     {rid:>2}         {x:>8.3f}         {y:>8.3f}"
                f"          1.000 0 1     0                           "
                f"  0.000000       0.000000 {pc_out:>2}  0  0"
            )
            L.append(f"C {loc:<50}")

        else:  # junction (type 3 or 4)
            L.append(
                f"C     {rid:>2}         {x:>8.3f}         {y:>8.3f}"
                f"          1.000 0 0     0 J8                        "
                f"   0.000000       0.000000 {pc:>2}  0  0"
            )
            L.append(f"C {n['name']:<50}")

    # ── #REACHES (none yet) ───────────────────────────────────────────────────
    L += ["C ", "C #REACHES", "C     0"]

    L += [
        "C ",
        "C #STORAGES",
        "C      0",
        "C ",
        "C #INFLOW/OUTFLOW",
        "C      0",
        "C ",
        "C END RORB_GE",
        "C ",
        "1",
    ]

    # ── control vector (minimal — all sub-areas join at outlet) ──────────────
    cv, area_order = _build_minimal_cv(nodes, sub_ids, outlet_id)
    L.extend(cv)

    # ── sub-area data ─────────────────────────────────────────────────────────
    L += ["C Sub Area Data", "C Areas, km**2, of subareas A,B..."]
    row = []
    for k, nid in enumerate(area_order):
        row.append(f"{nodes[nid]['area']:>12.5f},")
        if (k + 1) % 5 == 0:
            L.append("  " + " ".join(row)); row = []
    if row:
        L.append("  " + " ".join(row))

    L.append(" -99")
    L.append("C Impervious Fraction Data")
    if any(nodes[nid]['fi'] > 0 for nid in area_order):
        fi_row = []
        for k, nid in enumerate(area_order):
            fi_row.append(f"{nodes[nid]['fi']:>12.6f},")
            if (k + 1) % 5 == 0:
                L.append("  " + " ".join(fi_row)); fi_row = []
        if fi_row:
            L.append("  " + " ".join(fi_row))
        L.append(" -99")
    else:
        L.append(f"0,  -99{'':<42},No impervious areas in system")
    L.append(" ")

    return "\r\n".join(L)


def _build_minimal_cv(nodes, sub_ids, outlet_id):
    """Minimal control vector: all sub-areas with zero-length reaches, joined at outlet."""
    cv, area_order = [], list(sub_ids)

    if area_order:
        cv.append("1, 0.000,  -99")
        for _ in area_order[1:]:
            cv.append("3")
            cv.append("1, 0.000,  -99")
            cv.append("4")

    if outlet_id is not None:
        n = nodes[outlet_id]
        cv_code = {70: "7", 71: "71", 72: "72"}.get(
            n['print_code'] if n['print_node'] else 70, "7")
        loc = n['location'] or n['name'] or "Outlet"
    else:
        cv_code, loc = "7", "Outlet"

    cv += [cv_code, loc, "0"]
    return cv, area_order
